package ru.fabrikant.api.multi_integration.easuz.method;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-01T20:15:29.913+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "EASUZIntegrationService", 
                  wsdlLocation = "file:src/test/resources/easuz.wsdl",
                  targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method") 
public class EASUZIntegrationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://api.fabrikant.ru/multi-integration/easuz/method", "EASUZIntegrationService");
    public final static QName BasicHttpBindingIEASUZIntegrationService = new QName("http://api.fabrikant.ru/multi-integration/easuz/method", "BasicHttpBinding_IEASUZIntegrationService");
    static {
        URL url = null;
        try {
            url = new URL("file:src/test/resources/easuz.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EASUZIntegrationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:src/test/resources/easuz.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EASUZIntegrationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EASUZIntegrationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EASUZIntegrationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public EASUZIntegrationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EASUZIntegrationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EASUZIntegrationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     * API торгово-закупочных процедур.
     *
     * @return
     *     returns IEASUZIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEASUZIntegrationService")
    public IEASUZIntegrationService getBasicHttpBindingIEASUZIntegrationService() {
        return super.getPort(BasicHttpBindingIEASUZIntegrationService, IEASUZIntegrationService.class);
    }

    /**
     * API торгово-закупочных процедур.
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEASUZIntegrationService
     */
    @WebEndpoint(name = "BasicHttpBinding_IEASUZIntegrationService")
    public IEASUZIntegrationService getBasicHttpBindingIEASUZIntegrationService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIEASUZIntegrationService, IEASUZIntegrationService.class, features);
    }

}
