package ru.fabrikant.api.multi_integration.easuz.method;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-01T20:15:29.743+03:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", name = "IEASUZIntegrationService")
@XmlSeeAlso({ru.fabrikant.api.multi_integration.easuz.prepareprocedure.ObjectFactory.class, ru.fabrikant.api.multi_integration.easuz.downloadfile.ObjectFactory.class, ru.fabrikant.api.multi_integration.easuz.uploadfile.ObjectFactory.class, ru.fabrikant.api.multi_integration.easuz.protocol.ObjectFactory.class, ObjectFactory.class, ru.fabrikant.api.multi_integration.easuz.procedureinfo.ObjectFactory.class, ru.fabrikant.api.multi_integration.easuz.types.ObjectFactory.class})
public interface IEASUZIntegrationService {

    @WebMethod(operationName = "PrepareAuction", action = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareAuction")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareAuction", output = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareAuctionResponse")
    @RequestWrapper(localName = "PrepareAuction", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.prepareprocedure.PrepareAuction")
    @ResponseWrapper(localName = "MessageAccepted", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.method.MessageAccepted")
    public void prepareAuction(
        @WebParam(name = "Header", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.types.Header header,
        @WebParam(name = "PurchaseId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        java.lang.String purchaseId,
        @WebParam(name = "AuctionType", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.prepareprocedure.AuctionType auctionType,
        @WebParam(name = "Auction", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.prepareprocedure.Auction auction,
        @WebParam(mode = WebParam.Mode.OUT, name = "RequestId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "EstimateTime", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.math.BigInteger> estimateTime
    );

    @WebMethod(operationName = "PrepareProcedurePurchase", action = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareProcedurePurchase")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareProcedurePurchase", output = "http://api.fabrikant.ru/multi-integration/easuz/method/PrepareProcedurePurchaseResponse")
    @RequestWrapper(localName = "PrepareProcedurePurchase", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.prepareprocedure.PrepareProcedurePurchase")
    @ResponseWrapper(localName = "MessageAccepted", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.method.MessageAccepted")
    public void prepareProcedurePurchase(
        @WebParam(name = "Header", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.types.Header header,
        @WebParam(name = "PurchaseId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        java.lang.String purchaseId,
        @WebParam(name = "ProcedurePurchaseType", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.prepareprocedure.ProcedurePurchaseType procedurePurchaseType,
        @WebParam(name = "Purchase", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/prepareProcedure/")
        ru.fabrikant.api.multi_integration.easuz.prepareprocedure.ProcedurePurchase purchase,
        @WebParam(mode = WebParam.Mode.OUT, name = "RequestId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "EstimateTime", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.math.BigInteger> estimateTime
    );

    @WebMethod(operationName = "CheckRequest", action = "http://api.fabrikant.ru/multi-integration/easuz/method/CheckRequest")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/CheckRequest", output = "http://api.fabrikant.ru/multi-integration/easuz/method/CheckRequestResponse")
    @RequestWrapper(localName = "CheckRequest", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.method.CheckRequest")
    @ResponseWrapper(localName = "CheckRequestResponse", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.method.CheckRequestResponse")
    public void checkRequest(
        @WebParam(mode = WebParam.Mode.INOUT, name = "RequestId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ResponseIsReady", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.lang.Boolean> responseIsReady,
        @WebParam(mode = WebParam.Mode.OUT, name = "Response", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<ResponseData> response
    );

    @WebMethod(operationName = "GetFile", action = "http://api.fabrikant.ru/multi-integration/easuz/method/GetFile")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/GetFile", output = "http://api.fabrikant.ru/multi-integration/easuz/method/GetFileResponse")
    @RequestWrapper(localName = "GetFile", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.downloadfile.GetFile")
    @ResponseWrapper(localName = "GetFileResponse", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.downloadfile.GetFileResponse")
    public void getFile(
        @WebParam(mode = WebParam.Mode.INOUT, name = "FileId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/downloadFile/")
        javax.xml.ws.Holder<java.lang.String> fileId,
        @WebParam(mode = WebParam.Mode.OUT, name = "FileInstance", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/downloadFile/")
        javax.xml.ws.Holder<ru.fabrikant.api.multi_integration.easuz.types.FileInstance> fileInstance
    );

    @WebMethod(operationName = "UploadProcedureFile", action = "http://api.fabrikant.ru/multi-integration/easuz/method/UploadProcedureFile")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/UploadProcedureFile", output = "http://api.fabrikant.ru/multi-integration/easuz/method/UploadProcedureFileResponse")
    @RequestWrapper(localName = "UploadProcedureFile", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.uploadfile.UploadProcedureFile")
    @ResponseWrapper(localName = "MessageAccepted", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.method.MessageAccepted")
    public void uploadProcedureFile(
        @WebParam(name = "Header", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/uploadFile/")
        ru.fabrikant.api.multi_integration.easuz.types.Header header,
        @WebParam(name = "PurchaseId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/uploadFile/")
        java.lang.String purchaseId,
        @WebParam(name = "LotId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/uploadFile/")
        java.lang.String lotId,
        @WebParam(name = "FileId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/uploadFile/")
        java.lang.String fileId,
        @WebParam(name = "FileInstance", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/uploadFile/")
        ru.fabrikant.api.multi_integration.easuz.types.FileInstance fileInstance,
        @WebParam(mode = WebParam.Mode.OUT, name = "RequestId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.lang.String> requestId,
        @WebParam(mode = WebParam.Mode.OUT, name = "EstimateTime", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        javax.xml.ws.Holder<java.math.BigInteger> estimateTime
    );

    @WebMethod(operationName = "GetProtocol", action = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProtocol")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProtocol", output = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProtocolResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetProtocolResponse", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", partName = "parameters")
    public ru.fabrikant.api.multi_integration.easuz.protocol.GetProtocolResponse getProtocol(
        @WebParam(partName = "parameters", name = "GetProtocol", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method")
        ru.fabrikant.api.multi_integration.easuz.protocol.GetProtocol parameters
    );

    @WebMethod(operationName = "GetProcedureInfo", action = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProcedureInfo")
    @Action(input = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProcedureInfo", output = "http://api.fabrikant.ru/multi-integration/easuz/method/GetProcedureInfoResponse")
    @RequestWrapper(localName = "GetProcedureInfo", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.procedureinfo.GetProcedureInfo")
    @ResponseWrapper(localName = "GetProcedureInfoResponse", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/method", className = "ru.fabrikant.api.multi_integration.easuz.procedureinfo.GetProcedureInfoResponse")
    public void getProcedureInfo(
        @WebParam(name = "Header", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/procedureInfo/")
        ru.fabrikant.api.multi_integration.easuz.types.Header header,
        @WebParam(name = "PurchaseId", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/procedureInfo/")
        java.lang.String purchaseId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ProcedureUrl", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/procedureInfo/")
        javax.xml.ws.Holder<java.lang.String> procedureUrl,
        @WebParam(mode = WebParam.Mode.OUT, name = "ProcedureNumber", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/procedureInfo/")
        javax.xml.ws.Holder<java.lang.String> procedureNumber,
        @WebParam(mode = WebParam.Mode.OUT, name = "LotInfoList", targetNamespace = "http://api.fabrikant.ru/multi-integration/easuz/procedureInfo/")
        javax.xml.ws.Holder<ru.fabrikant.api.multi_integration.easuz.procedureinfo.GetProcedureInfoResponse.LotInfoList> lotInfoList
    );
}
